### ISSUE TITLE
clear most of these todo's

### ISSUE THREAD

**Issue by edrickhong** [edrickhong/Cu#31]
- [ ] src/cparser/main.cpp:7:  TODO: 
- [ ] src/cparser/main.cpp:15://TODO: struct union and enum have the same parse structure (should we condense here?)
- [ ] src/cparser/main.cpp:85://TODO: prep this to move into pparse
- [ ] src/cparser/main.cpp:221:    //TODO: we shouldn't need to do this
- [ ] src/cparser/main.cpp:289:        TODO: I do not like how initialization is done rn
- [ ] src/cparser/main.cpp:460://TODO: allow pouinter types
- [ ] src/cparser/main.h:22://TODO: these are not generic enought (int etc. do that and we can move this to pparse)
- [ ] src/cparser/main.h:437:                //TODO: support more than 1d arrays
- [ ] 
- [ ] src/cu_std/cu/mmath.cpp:1://TODO: I actually don't know if inverse works in column major
- [ ] src/cu_std/cu/mmath.cpp:1499:    //TODO:since we are only rotating one point, we should optimize for this case here
- [ ] src/cu_std/cu/mmath.cpp:1627://TODO: this is very inefficient. we can solve this in 2d space easier
- [ ] src/cu_std/cu/mmath.cpp:1641://TODO: this is very inefficient. we can solve this in 2d space easier
- [ ] 
- [ ] 
- [ ] src/cu_std/cu/pparse.cpp:310:                    //TODO: handle this
- [ ] src/cu_std/cu/pparse.h:13:TODO: we should make size or pos to ptrsize instead of u32
- [ ] src/cu_std/cu/pparse.h:255://TODO:
- [ ] 
- [ ] 
- [ ] src/cu_std/cu/vvulkan.cpp:2796://TODO: VkSampleMask* samplemask is a dependency (do we not save it?)
- [ ] 
- [ ] src/cu_std/linux/wayland_wwindow.cpp:216:    //TODO: we might want to free if already initialized?
- [ ] src/cu_std/linux/wayland_wwindow.cpp:513:        //TODO: disconnect display and xkb_ctx

**Comment by edrickhong** [comment]
We should take a look at refactoring the vulkan interface. I am considering writing an api on top of vulkan that is easier to work with (saner defaults and ease of use features. will be very thin and will standardize stuff like multigpu. will subset a batch of extensions to a feature set)
