### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by edrickhong** [edrickhong/Cu#8]
List of things to do. Try to complete some of them within the next 2 months

**Misc**
- [ ] Asset packer
- [ ] Settings parser (Text based. should store properties like window dimensions etc. Must be text editable. Provide a function to fetch and write the value. )
- [ ] Transition to Vulkan 1.1 (VkDevice creation should be using done using a device group and vkCmd* should take in a device mask *read the spec for more details*. In the case where 1.1 is not available, fallback to 1.0 using an individual physical device. vkCmd* masks will be ignored)
- [ ] VT texture feedback buffer should write a material ID instead of a texture ID, then the individual textures will be fetched from each material

**GUI improvements** (gui_draw - This is immediate mode GUI. Refer to IMGUI or read up on immediate mode GUI vs retained mode GUI to know the difference)
- [ ] Color picker
- [ ] Slider
- [ ] Resize-able GUI windows
- [ ] Checkboxes
- [ ]  Scrolling in the window (scrollbar etc) 

**Debugging**
- [ ] Log all open files for Windows. (Refer to Linux. The exact same code should work but win32 file handles are 64 bit on 64 bit machines, so the LockCmpXchg has to be the 64 bit version. You can find the implementation in amd64 folder)
- [ ] Track alloc calls - alloc, unalloc, realloc (the first two are wrappers to malloc and free. write a wrapper for realloc)

**Audio**
- [ ] Support Ogg compressed sound. Compress the audio to our internal ADF format. The decoder has to be self implemented. You can use an encoder from a library but try to keep it to a header only library (eg stb_*.h libs)
- [ ] SIMD audio mixing. Current audio mixing doesn't use SIMD capabilities
- [ ] 
- [ ] Audio pitch shifter. Basically Changing the speed of the given audio. Can be done by compressing the signal aka removing audio samples, or generating in between samples to lengthen the audio. DO NOT change the sample rate of the audio device. That is not what we want

**Comment by edrickhong** [comment]
**TO SELF**

Finish these before moving onto console commands
